monitor.bluez.properties = {
  bluez5.auto-connect = [ a2dp_sink a2dp_source ]
  bluez5.default.rate = 48000
}

monitor.bluez.rules = [
  {
    matches = [
      { device.name = "~bluez_card.*" }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink a2dp_source ]
        bluez5.headset-roles = [ ]
      }
    }
  }
]
